/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author guilh
 */
public class Calculadora extends javax.swing.JFrame {

    int valorPress;
    int valorPress2;
    int valorPosResul;
    double resultado;
    String op;

    public Calculadora() {
        initComponents();
        valorPress = 0;
        resultado = -1;
        valorPosResul = 0;
        valorPress2 = 0;
        op = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        resultadoFinal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        quatro = new javax.swing.JButton();
        sete = new javax.swing.JButton();
        oito = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        um = new javax.swing.JButton();
        dois = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        multiplica = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        subtrai = new javax.swing.JButton();
        soma = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        ce = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultadoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadoFinal)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );

        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });

        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });

        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });

        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        multiplica.setText("*");
        multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        subtrai.setText("-");
        subtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtraiActionPerformed(evt);
            }
        });

        soma.setText("+");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        ce.setText("CE");
        ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(igual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(multiplica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(divide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ce)
                        .addGap(80, 80, 80)
                        .addComponent(subtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ce))
                .addGap(73, 73, 73)
                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(multiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        if (valorPress != 0 && resultado == -1) {
            valorPress2 = 7;
            resultadoFinal.setText(resultadoFinal.getText() + 7);
            System.out.println("Entrou if");
            System.out.println("v1: " + valorPress);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 7;
            resultadoFinal.setText(resultadoFinal.getText() + 7);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 7;
            resultadoFinal.setText(resultadoFinal.getText() + 7);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_seteActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        if (valorPress != 0 && resultado == -1) {
            valorPress2 = 9;
            resultadoFinal.setText(resultadoFinal.getText() + 9);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 9;
            resultadoFinal.setText(resultadoFinal.getText() + 9);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 9;
            resultadoFinal.setText(resultadoFinal.getText() + 9);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_noveActionPerformed

    private void subtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtraiActionPerformed
        op = "Su";
        resultadoFinal.setText(resultadoFinal.getText() + " - ");
    }//GEN-LAST:event_subtraiActionPerformed

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
        op = "So";
        resultadoFinal.setText(resultadoFinal.getText() + " + ");
    }//GEN-LAST:event_somaActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        String re;
        if ("So".equals(op) && resultado == -1) {
            resultado = valorPress + valorPress2;
            re = Double.toString(resultado);
            resultadoFinal.setText(re);
            System.out.println("resul: "+resultado);
        } else if ("Su".equals(op) && resultado == -1) {
            resultado = valorPress - valorPress2;
            re = Double.toString(resultado);
            resultadoFinal.setText(re);
        } else if ("M".equals(op) && resultado == -1) {
            resultado = (valorPress * valorPress2);
            re = Double.toString(resultado);
            resultadoFinal.setText(re);
        } else if ("D".equals(op) && resultado == -1) {
            resultado = (valorPress / valorPress2);
            re = Double.toString(resultado);
            resultadoFinal.setText(re);
        } else {
            if (null != op) {
                switch (op) {
                    case "So":
                        System.out.println("valor pos: "+valorPosResul);
                        resultado = resultado + valorPosResul;
                        re = Double.toString(resultado);
                        resultadoFinal.setText(re);
                        System.out.println("resul: "+resultado);
                        break;
                    case "Su":
                        resultado = resultado - valorPosResul;
                        re = Double.toString(resultado);
                        resultadoFinal.setText(re);
                        break;
                    case "M":
                        resultado = resultado * valorPosResul;
                        re = Double.toString(resultado);
                        resultadoFinal.setText(re);
                        break;
                    case "D":
                        resultado = resultado / valorPosResul;
                        re = Double.toString(resultado);
                        resultadoFinal.setText(re);
                        break;
                    default:
                        break;
                }
            }
        }

    }//GEN-LAST:event_igualActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        op = "D";
        resultadoFinal.setText(resultadoFinal.getText() + " / ");
    }//GEN-LAST:event_divideActionPerformed

    private void multiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaActionPerformed
        op = "M";
        resultadoFinal.setText(resultadoFinal.getText() + " * ");
    }//GEN-LAST:event_multiplicaActionPerformed

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroActionPerformed
        if (valorPress != 0 && resultado == -1) {
            valorPress2 = 4;
            resultadoFinal.setText(resultadoFinal.getText() + 4);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 4;
            resultadoFinal.setText(resultadoFinal.getText() + 4);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 4;
            resultadoFinal.setText(resultadoFinal.getText() + 4);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_quatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        if (valorPress != 0&& resultado == -1) {
            valorPress2 = 5;
            resultadoFinal.setText(resultadoFinal.getText() + 5);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 5;
            resultadoFinal.setText(resultadoFinal.getText() + 5);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 5;
            resultadoFinal.setText(resultadoFinal.getText() + 5);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        if (valorPress != 0&& resultado == -1) {
            valorPress2 = 6;
            resultadoFinal.setText(resultadoFinal.getText() + 6);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 6;
            resultadoFinal.setText(resultadoFinal.getText() + 6);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 6;
            resultadoFinal.setText(resultadoFinal.getText() + 6);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_seisActionPerformed

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
        if (valorPress != 0&& resultado == -1) {
            valorPress2 = 1;
            resultadoFinal.setText(resultadoFinal.getText() + 1);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 1;
            resultadoFinal.setText(resultadoFinal.getText() + 1);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 1;
            resultadoFinal.setText(resultadoFinal.getText() + 1);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_umActionPerformed

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisActionPerformed
        if (valorPress != 0&& resultado == -1) {
            valorPress2 = 2;
            resultadoFinal.setText(resultadoFinal.getText() + 2);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 2;
            resultadoFinal.setText(resultadoFinal.getText() + 2);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 7;
            resultadoFinal.setText(resultadoFinal.getText() + 2);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_doisActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        if (valorPress != 0&& resultado == -1) {
            valorPress2 = 3;
            resultadoFinal.setText(resultadoFinal.getText() + 3);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 3;
            resultadoFinal.setText(resultadoFinal.getText() + 3);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 3;
            resultadoFinal.setText(resultadoFinal.getText() + 3);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_tresActionPerformed

    private void resultadoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoFinalActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        if (valorPress != 0 && resultado == -1) {
            valorPress2 = 8;
            resultadoFinal.setText(resultadoFinal.getText() + 8);
        } else if (valorPress2 == 0 && resultado == -1) {
            valorPress = 8;
            resultadoFinal.setText(resultadoFinal.getText() + 8);
            System.out.println("Entrou elif");
            System.out.println("op: " + op);
        } else {
            valorPosResul = 8;
            resultadoFinal.setText(resultadoFinal.getText() + 8);
            System.out.println("Entrou else");
            System.out.println("op: " + op);
        }
    }//GEN-LAST:event_oitoActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceActionPerformed
        valorPress = 0;
        valorPress2 = 0;
        resultadoFinal.setText("");
        resultado = -1;
        valorPosResul = 0;
    }//GEN-LAST:event_ceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ce;
    private javax.swing.JButton cinco;
    private javax.swing.JButton divide;
    private javax.swing.JButton dois;
    private javax.swing.JButton igual;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multiplica;
    private javax.swing.JButton nove;
    private javax.swing.JButton oito;
    private javax.swing.JButton quatro;
    private javax.swing.JTextField resultadoFinal;
    private javax.swing.JButton seis;
    private javax.swing.JButton sete;
    private javax.swing.JButton soma;
    private javax.swing.JButton subtrai;
    private javax.swing.JButton tres;
    private javax.swing.JButton um;
    // End of variables declaration//GEN-END:variables
}
